### ISSUE TITLE
Add Redis methods

### ISSUE THREAD

**Issue by maxwai** [marcelropos/HM-DiscordBot#137]
Add Methods to write/read/delete the channel id of the main log pipe.

Also add Methods to write/read/delete email addresses and the infos involved with them.
The addresses are stored as a hash (this is the key of an entry) and the value of the entry will be a string of 2 numbers combined (see below).
The numbers that need to be saved are the amount of times the email was used and the amount of times the email verified someone.

Also add convenience Methods to quickly increment a number for an email address.

All Methods will take in the email address instead of the hash.

The numbers are saved as such: `<num1>,<num2>`

**Comment by schitcrafter** [comment]
I could implement this

**Comment by schitcrafter** [comment]
Which hash function should I use for hashing the emails?

**Comment by maxwai** [comment]
Closed with #187
