### ISSUE TITLE
Add command to add log pipe

### ISSUE THREAD

**Issue by maxwai** [marcelropos/HM-DiscordBot#159]
Add Command so that a Guild admin can add a log pipe into a channel.

The command should be a little different if done in the main guild.

**Comment by schitcrafter** [comment]
I could work on this, would make sense since I made the logging stuff.

**Comment by maxwai** [comment]
Sure go for it

**Comment by schitcrafter** [comment]
Bot.md says "Permission: Guild admin, bot admin" - we have `checks::is_admin()` and `checks::is_owner()` for the first one (guild admin), but I'm not seeing anything for bot admin...is this implemented already and I've just missed it? Or is this still todo?

**Comment by maxwai** [comment]
The Bot admin is anyone that is an admin on the main guild. Normally commands for bot admins can only be used in the main guild. If this is not the case in the current description, let me know and I will look at it.

**Comment by schitcrafter** [comment]
It's documented, in Bot.md under the section "Storage"
